name: isr_afil_blog_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  font_awesome_flutter: ^10.8.0
  cloudinary: ^1.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  mime: ^2.0.0
  ffi: ^2.1.3
  url_launcher: ^6.3.1
  image: ^4.5.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true