// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU9Hign1ohm5PcqaKLwOF1lODqnPT9BW0',
    appId: '1:807608578680:web:f68dd4431ac98e28f1338d',
    messagingSenderId: '807608578680',
    projectId: 'israfil-blog',
    authDomain: 'israfil-blog.firebaseapp.com',
    storageBucket: 'israfil-blog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ3lBHPlww4x5ulsTlXwhbDFyepu88DMQ',
    appId: '1:807608578680:android:bd11164ff549c7d9f1338d',
    messagingSenderId: '807608578680',
    projectId: 'israfil-blog',
    storageBucket: 'israfil-blog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JzVLPvXadMwHgnHtOEqK7C5djCEKFs8',
    appId: '1:807608578680:ios:7ceffe3af2e8916cf1338d',
    messagingSenderId: '807608578680',
    projectId: 'israfil-blog',
    storageBucket: 'israfil-blog.appspot.com',
    iosBundleId: 'com.example.isrAfilBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JzVLPvXadMwHgnHtOEqK7C5djCEKFs8',
    appId: '1:807608578680:ios:7ceffe3af2e8916cf1338d',
    messagingSenderId: '807608578680',
    projectId: 'israfil-blog',
    storageBucket: 'israfil-blog.appspot.com',
    iosBundleId: 'com.example.isrAfilBlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU9Hign1ohm5PcqaKLwOF1lODqnPT9BW0',
    appId: '1:807608578680:web:7293322facb25167f1338d',
    messagingSenderId: '807608578680',
    projectId: 'israfil-blog',
    authDomain: 'israfil-blog.firebaseapp.com',
    storageBucket: 'israfil-blog.appspot.com',
  );
}
